/*---------------------------------------------------------
  pictures.c
---------------------------------------------------------*/

#include "pictures.h"

#ifdef PICTURE8
#  include "material8.dat"
#  include "usb8.dat"
#  include "power8.dat"
#  include "LowPower8.dat"
#  include "ChargeDark8.dat"
#  include "ChargeLight8.dat"
#  include "SpinUp8.dat"
#  include "SpinDown8.dat"
#  include "SmallSpinUp8.dat"
#  include "SmallSpinDown8.dat"
#  include "rectangle8.dat"
#  include "circle8.dat"
#  include "Checked8.dat"
#  include "UnChecked8.dat"
#  include "ArrowRight8.dat"
#  include "ArrowLeft8.dat"
#  include "ArrowTop8.dat"
#  include "MenuDown8.dat"
#  include "MenuUp8.dat"
#  include "chart_f8.dat"
#  include "chart_3k8.dat"
#  include "chart_30k8.dat"
#  include "chart_t8.dat"
#  include "chart_908.dat"
#else
#  include "material16.dat"
#  include "usb16.dat"
#  include "power16.dat"
#  include "LowPower16.dat"
#  include "ChargeDark16.dat"
#  include "ChargeLight16.dat"
#  include "SpinUp16.dat"
#  include "SpinDown16.dat"
#  include "SmallSpinUp16.dat"
#  include "SmallSpinDown16.dat"
#  include "rectangle16.dat"
#  include "circle16.dat"
#  include "Checked16.dat"
#  include "UnChecked16.dat"
#  include "ArrowRight16.dat"
#  include "ArrowLeft16.dat"
#  include "ArrowTop16.dat"
#  include "MenuDown16.dat"
#  include "MenuUp16.dat"
#  include "chart_f16.dat"
#  include "chart_3k16.dat"
#  include "chart_30k16.dat"
#  include "chart_t16.dat"
#  include "chart_9016.dat"
#endif
